### ISSUE TITLE
High Resolution / DPI issues

### ISSUE THREAD

**Issue by SebastianK90** [bengtmartensson/IrScrutinizer#99]
Hi there could you adjust IrScrutinizer for high Resolution?
At the moment on a 4K Resolution it's not really usable!
![2016-01-30 19_54_48-program manager](https://cloud.githubusercontent.com/assets/12467271/12697766/5dfdcee6-c78b-11e5-81ae-49535b69a8b3.png)

**Comment by bengtmartensson** [comment]
I am not sure what point you want to make. The screen shot shows that when the GUI is "ridiculously" expanded, it behaves well -- everything is readable, nothing overlaps, what should go right goes right, etc.

If you request that the GUI should look "optimized for 3840 x 2160" I simply reject that request -- it is not meant for that. Just don't maximize and you are set. 

If you mean that larger user interface elements are needed (font, icons, buttons etc) are needed/wanted due to DPI >> 96 or other reason ("accessability") that might be more sensible. Feel free to submit patches and push requests. To me, there are so many more important things, 

Make sure you are using the very latest Java.

**Comment by sippi90** [comment]
Yes please add lager user interface elements

**Comment by bengtmartensson** [comment]
for the one wanting to work on this: cf https://github.com/arduino/Arduino/pull/4376

**Comment by bengtmartensson** [comment]
Possibly relevant: https://github.com/arduino/Arduino/pull/5556

**Comment by bengtmartensson** [comment]
Basically everything (or almost everything) should be scalable and the scaling determined by -- what? I have looked at the Arduino IDE and Firefox, and basically learned that there is no easy and immediate solution.

But I still consider most uses of "maximize" silly, an artifact from MS-DOS...

Anyone who is willing and able to help?

**Comment by bengtmartensson** [comment]
https://wiki.archlinux.org/index.php/HiDPI#AWT/Swing seems to be at least a crude, solution.
Also see https://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html

**Comment by bengtmartensson** [comment]
There is a --scale argument, recently improved (#513), that may be satisfying for the original poster. Using the redhat Java 17 on Fedora, it looks quite good to me. Still. it is not a perfect solution, but that lies within Java/Swing. For that reason, I do not think it is meaningful to keep this issue open.
